### ISSUE TITLE
1.3 GPU links are dead

### ISSUE THREAD

**Issue by yaroslavvb** [mind/wheels#1]
https://github.com/mind/wheels/releases/download/tf1.3-gpu/tensorflow-1.3-cp36-cp36m-linux_x86_64.whl

**Comment by yaroslavvb** [comment]
Hm, looks like these wheels are for Ubuntu 16.04....a lot of amazon images are still Ubuntu 14.04, also Travis doesn't support 16.04 yet https://docs.travis-ci.com/user/reference/overview/

**Comment by vmarkovtsev** [comment]
The reason is simple: it is `https://github.com/mind/wheels/releases/download/tf1.3-gpu/tensorflow-1.3.0-cp36-cp36m-linux_x86_64.whl` instead. Mind ".0" added to the version.

**Comment by danqing** [comment]
Thanks for the catch @vmarkovtsev ! Added the .0

@yaroslavvb unfortunately there's no plan to support 14.04. We do not have any 14.04 machines in our environment. Consider using [Docker images](https://hub.docker.com/r/tinymind/tensorflow/) if you have environment constraints.
