### ISSUE TITLE
Can you built a wheel without MKL?

### ISSUE THREAD

**Issue by Cescfangs** [mind/wheels#10]
I am trying to install tensorflow-gpu on servers(CUDA9) where I have no access to `sudo` .

**Comment by danqing** [comment]
Sure, we can provide one. What's your Python version?

**Comment by Cescfangs** [comment]
python3.6, thanks mate!

**Comment by amberfly** [comment]
Try https://github.com/mind/wheels/releases/tag/tf1.4-gpu-cuda9-nomkl

**Comment by Cescfangs** [comment]
it worked without MKL, but require GLIBC_2.23...sad

**Comment by danqing** [comment]
There are some discussions in #7. I assume if you don't install it under `/opt` you won't need `sudo`, and then you can just link it like the last commenter described to make it work.

(In fact you may not need `sudo` for `/opt`..)

**Comment by Cescfangs** [comment]
#7 acctually solved my problem, thanks guys!!!

**Comment by danqing** [comment]
Awesome. Thanks for letting us know!
