### ISSUE TITLE
Will the Cuda capability 3.5 be supported?

### ISSUE THREAD

**Issue by Jiramew** [mind/wheels#13]
Thanks so much for your work, it's awesome!

Will the minimum required Cuda capability be set to 3.5 when building? Or where can i configure it?

Thanks so much. ^o^
Best Regards.

**Comment by danqing** [comment]
We will consider it! Which python version do you use?

**Comment by Jiramew** [comment]
@danqing Python 3.6, Thanks so much~

**Comment by amberfly** [comment]
Give this a try and see if it suits your needs. Be sure to upgrade to 9.1 if you are on CUDA 9.

https://github.com/mind/wheels/releases/tag/tf-adhoc

Feel free to reopen if you have issues with it.
