### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by godshades** [mind/wheels#18]
OS: win 10 64 bit
python 3.6 64 bit
cuda 9.1

I try pip --no-cache-dir install https://github.com/mind/wheels/releases/download/tf1.4.1-gpu-cuda91/tensorflow-1.4.0-cp36-cp36m-linux_x86_64.whl
But It's say "tensorflow-1.4.0-cp36-cp36m-linux_x86_64.whl is not a supported wheel on this platform."

help

**Comment by Moulick** [comment]
As said in the ReadMe, these wheels are for Ubuntu specific. They cannot be installed on Windows Machines.
