### ISSUE TITLE
Debug builds?

### ISSUE THREAD

**Issue by yaroslavvb** [mind/wheels#2]
Would you be interested in providing versions of TensorFlow with symbol tables? That would make it much easier to troubleshoot segfaults.

Optimized build with symbol tables: (almost as fast, lets you query local variables in gdb)
`blaze build --cxxopt=-g2 --linkopt=-g2 --strip never -c opt
`

Fully debuggable build (ie, gives line numbers, but can be 10x slower) 
`blaze build -c dbg`

**Comment by danqing** [comment]
Good suggestion. Will try to get some of these!

**Comment by yaroslavvb** [comment]
That be great! With symbol tables you can do magic like this to get values of local variables

```
ulimit -Sc unlimited
python crashy_tensorflow.py
gdb python
core core
frame 2
info locals

```

**Comment by danqing** [comment]
Ok, I'm gonna start getting debug builds. Which of the two is more useful? May not be able to get both at once (for now, at least)

**Comment by yaroslavvb** [comment]
go for `-c dbg` first

**Comment by danqing** [comment]
Closing this. Will try to keep a debug build around for each version onward.
