### ISSUE TITLE
cuda 9.1 issue.

### ISSUE THREAD

**Issue by jihaonew** [mind/wheels#20]
- ubuntu 17.10
- cuda 9.1, cudnn 7
- GPU: nvidia P40

I met a problem.
```bash
ImportError: libcudnn.so.7: cannot open shared object file: No such file or directory
```
I have already add the environment variables.
```
export CUDA_HOME=/usr/local/cuda
export PATH=$PATH:$CUDA_HOME/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CUDA_HOME/lib64
```

I run the command:
```bash
ls -l /usr/local/cuda/lib64/libcudn*
```
I get the following result:
```
-rwxr-xr-x 1 root root 282621088 1月  18 11:27 /usr/local/cuda/lib64/libcudnn.so
-rwxr-xr-x 1 root root 282621088 1月  18 11:27 /usr/local/cuda/lib64/libcudnn.so.7
-rwxr-xr-x 1 root root 282621088 1月  18 11:27 /usr/local/cuda/lib64/libcudnn.so.7.0.5
-rw-r--r-- 1 root root 277149668 1月  18 11:27 /usr/local/cuda/lib64/libcudnn_static.a
```
I think the output above shows that the cuda and cudnn are already installed in my computer.

**Comment by danqing** [comment]
Try `sudo ldconfig /usr/local/cuda/lib64`.

I'm not sure if wheels here work with 17.10. If earlier wheels did then there's something wrong with your setup. If the above doesn't do it, try do a fresh install of CUDA/cuDNN.

**Comment by jihaonew** [comment]
My OS is Ubuntu 16.04. I tried ```sudo ldconfig```, didn't work for me. 
I will try to reinstall CUDA/cuDNN and try again.

**Comment by Moulick** [comment]
The wheels here are working on 17.10, 1.4.1 with Cuda9 one atleast.

**Comment by jihaonew** [comment]
Thank you so much! It works very well.
