### ISSUE TITLE
Which exact target architecture are these wheels compiled for?

### ISSUE THREAD

**Issue by Dobiasd** [mind/wheels#24]
What flags are actually given to the compiler (`-march=...`), i.e. what parameters is `bazel` called with? (`--copt=-mavx2`, `--copt=-mfma` etc.)

And is `g++` or `clang++` used?

**Comment by amberfly** [comment]
Hi there, we have `mavx`, `mavx2`, `msse4.1`, `mssr4.2`, `mfma`, `mfpmath=both` and we don't use clang.

**Comment by Moulick** [comment]
What would be the difference if clang++ was used instead of g++?

**Comment by amberfly** [comment]
My impression is that clang is more suited for macOS as it doesn't ship gcc by default.

**Comment by Dobiasd** [comment]
Thanks a lot! Do you think it would make sense to add this information to the README?

**Comment by danqing** [comment]
Added.
