### ISSUE TITLE
Please add Tensorflow-gpu 1.6 compiled with cuda 9.1 

### ISSUE THREAD

**Issue by janiteja** [mind/wheels#29]

**Comment by hienphamlabs** [comment]
+1

**Comment by MSC19950601** [comment]
+1

**Comment by danqing** [comment]
Builds with MKL can be found [here](https://github.com/mind/wheels/releases/tag/tf1.6-gpu-cuda91). Builds without MKL will come tomorrow.

**Comment by ghost** [comment]
@danqing Thanks for the quick response!
