### ISSUE TITLE
Plans to include XLA?

### ISSUE THREAD

**Issue by matthiasplappert** [mind/wheels#3]
This is a very useful repository! Do you guys have any plans to include XLA support in future builds? I realize that it is still an experimental feature, but it would be quite useful to have a build around that supports it. TF is also configured to disable this by default, so it would not change the overall behavior of the wheels you guys provide.

**Comment by yaroslavvb** [comment]
fyi, for non-standard ./configure options in an automated build, one could use an expect script like [this](https://github.com/yaroslavvb/stuff/blob/ab45a0463f12942aef4561799523a2f80e56d7de/configure_tf_cpu.sh) to automate turning on XLA

**Comment by danqing** [comment]
Yeah good suggestion! We didn't include it as we didn't need it ourselves, but if there's demand, we will definitely add support for that.

Thanks for the issue!

**Comment by danqing** [comment]
I'm adding XLA builds for 1.3. Will include support for it in future builds as well. Closing this issue.
