### ISSUE TITLE
Loaded runtime CuDNN library: 7101 (compatibility version 7100) 

### ISSUE THREAD

**Issue by secretbatcave** [mind/wheels#33]
Hello there, 

firstly, thank you for producing these wheels, they are spectacularly useful. However I have run into a small compatibility issue. Nvidia have shipped cuDNN 7.1 in their cuda docker images, which is incompatible with your current 1.6 release. Running it yields: 

`E tensorflow/stream_executor/cuda/cuda_dnn.cc:378] Loaded runtime CuDNN library: 7101 (compatibility version 7100) but source was compiled with 7005 (compatibility version 7000).  If using a binary install, upgrade your CuDNN library to match.  If building from sources, make sure the library loaded at runtime matches a compatible version specified during compile configuration.`

If you would be so kind as to do a release built with cuDNN 7.1, that would be most wonderful.

**Comment by danqing** [comment]
Will provide with TF 1.7. Thanks for reporting!

**Comment by yangkang779** [comment]
thanks,How long does it take to update?  (tf1.7)

**Comment by secretbatcave** [comment]
@danqing Wonderful news!

**Comment by danqing** [comment]
https://github.com/mind/wheels/releases/tag/tf1.7-gpu-cuda91-nomkl

(python 3.6 coming soon)
