### ISSUE TITLE
We need update instruction for install MKL support

### ISSUE THREAD

**Issue by YerongLi** [mind/wheels#36]
Following MKL instruction here does not gives necessary  **libmklml_intel.so** file in the library.
 [https://github.com/mind/wheels#mkl](https://github.com/mind/wheels#mkl)

**Comment by danqing** [comment]
Just tested and it works. What OS do you use? Make sure you've added it to your PATH.

**Comment by danqing** [comment]
Closing. Feel free to reopen and provide more info if it still doesn't work.
