### ISSUE TITLE
tensorflow-gpu 1.8.0-rc1 wheel for cuda9.1 cudnn7.1 nccl2.1 py36 linux

### ISSUE THREAD

**Issue by kirk86** [mind/wheels#40]
Hi everyone I have just built a wheel for llinux with cuda 9.1 cudnn 7.1, nccl2.1 and python 3.6.
You can find it in the following [link!](https://github.com/kirk86/TensorFlow-GPU-1.8.0-rc1-Py36-cuda91-cudnn71-nccl21)
Maybe you wanna add it to the repository with the rest of the community wheels?

Cheers!

**Comment by danqing** [comment]
Thanks for providing the wheel. You may want to add it here: https://github.com/yaroslavvb/tensorflow-community-wheels.

**Comment by kirk86** [comment]
@danqing Thanks for the suggestion, I keep getting the following error

```
gsutil cp "tensorflow-1.8.0-cp36-cp36m-linux_x86_64.whl" "gs://tensorflow-community-wheels"
Copying file://tensorflow-1.8.0-cp36-cp36m-linux_x86_64.whl [Content-Type=application/octet-stream]...
ResumableUploadAbortException: 401 Anonymous caller does not have storage.objects.create access to tensorflow-community-wheels.
```
Any ideas what I'm missing. I'm using `gsutil` from pip. If I just issue `gsutil config` then it asks to pinpoint to a project id and nowhere there is `tensorflow-community-wheels` listed. I believe it must be sth really silly that I'm missing here?

**Comment by danqing** [comment]
I'm not quite sure what you are trying to achieve - are you looking for a GCS bucket? I'm not sure what that bucket is, but apparently it doesn't support anonymous writes.

**Comment by kirk86** [comment]
@danqing Thanks for getting back to me. As per the instructions [here](https://github.com/yaroslavvb/tensorflow-community-wheels), it is shown how to build and in the end of those instructions it shows how to copy your newly built wheel into the `tensorflow-community-wheels` google storage. 

> I'm not quite sure what you are trying to achieve

I'm trying to copy my wheel into the `tensorflow-community-wheels` google storage as you suggested in your first thread as well.
