### ISSUE TITLE
Any alternatives for someone with a 1060 and a rubbish AMD CPU?

### ISSUE THREAD

**Issue by maxisme** [mind/wheels#9]
Hello,

Would you be able to offer any advice on setting up with this library? As your setup is specifically for Intel CPUs.

I have cuda 9 and cuDNN v7.0.

Thanks

**Comment by danqing** [comment]
Wheels here are pretty much for Intel optimizations, which I guess isn't available to AMD CPUs. What are you looking for specifically?

**Comment by amberfly** [comment]
We've added [generic CUDA 9 wheels](https://github.com/mind/wheels/releases/tag/tf1.4-gpu-cuda9-generic) with no optimization. You may want to give them a try.
